server:
  port: 8082
# 服务名 环境设置 dev test prod
spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/guli?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
